import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NftPuller from './n2dpuller/nftpuller'
import Web3 from 'web3';
import NFTCollection from '../pages/n2dpuller/NFTCollection.json';


const ADDRESS = "0x1e52085B4BF5731Fa5e154C134c654aAeb4eabc8";
var  contract = null;
var account = null;
async function connectwallet() {
  if (window.ethereum) {
    var web3 = new Web3(window.ethereum);
    await window.ethereum.send('eth_requestAccounts');
    var accounts = await web3.eth.getAccounts();
    account = accounts[0];
    document.getElementById('walletAddress').textContent = account;
    contract = new web3.eth.Contract(NFTCollection, ADDRESS);
  }
}
async function mint() {
    if (window.ethereum) {
      var _mintAmount = Number(document.querySelector("[name=amount]").value);
      var mintRate = Number(await contract.methods.cost().call());
      var totalAmount = mintRate * _mintAmount; 
    contract.methods.mint(account, _mintAmount).send({ from: account, value: String(totalAmount)})
  }
}
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>C4U NFT Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h4 className={styles.title}>
          Welcome to <a href="https://distant.finance">C4U NFT Collection</a>
        </h4>
        <p>Dedicated to my loml, Loveth</p>

        <p className={styles.description}>
          <button onClick={connectwallet} >connect wallet</button>
        </p>

        <div className='card' id="walletAddress" style={{marginTop:"3px", boxShadow:"1px 1px 4px #000000"}}>
          
				</div>

        <div className={styles.grid}>
          <input type="number" name="amount" defaultValue="1" min="5"/>
          <label>please select the amount of NFT you want to buy MAX BUY IS 5 PER TRANSACTION</label>
          <button  onClick={mint} >Mint/Buy</button>
          
        </div>

        

      </main>
      <NftPuller />
      <footer className={styles.footer}>
        <a
          href="https://https://github.com/IbrahimIjai"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' DEV WHIZZIE '}
          <span className={styles.logo}>
            <Image src="" alt="" width={72} height={16} />
          </span>
        </a>
      </footer>
      
    </div> 
  )
}
